name: build

on:
  push:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          submodules: true
      - name: build plugin and loader
        run: |
          cmake -S . -B build -DIdaSdk_DIR=third_party/idasdk/src -DHexRaysSdk_ROOT_DIR=third_party/idasdk/src
          cmake --build build --config Release --parallel
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: efiXplorer64.dll
          path: build/plugin/Release/efiXplorer64.dll
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: efiXloader64.dll
          path: build/loader/Release/efiXloader64.dll

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          submodules: true
      - name: build plugin and loader
        run: |
          cmake -S . -B build -DIdaSdk_DIR=third_party/idasdk/src -DHexRaysSdk_ROOT_DIR=third_party/idasdk/src
          cmake --build build --config Release --parallel
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: efiXplorer64.so
          path: build/plugin/efiXplorer64.so
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: efiXloader64.so
          path: build/loader/efiXloader64.so

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          submodules: true
      - name: build plugin and loader
        run: |
          cmake -S . -B build -DIdaSdk_DIR=third_party/idasdk/src -DHexRaysSdk_ROOT_DIR=third_party/idasdk/src
          cmake --build build --config Release --parallel
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: efiXplorer64.dylib
          path: build/plugin/efiXplorer64.dylib
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: efiXloader64.dylib
          path: build/loader/efiXloader64.dylib
